### ISSUE TITLE
PHP examples

### ISSUE THREAD

**Issue by MrMooky** [Payop/payop-api-doc#45]
Hi there,

your documentation seems a bit slim. Do you guys have a PHP library to install or how does it work? I was not able to find any ways on how to get started with actual examples. Only some response examples, but that is not helping getting started.

**Comment by madmis** [comment]
Hi @MrMooky 

This is an API documentation. That's why it has only API request/response examples. 

If you need help with first steps (like registration, verification, etc...), please contact [support team](https://payop.com/en/contact-us). They will help you with this.

If you need more technical details about integration, in short (but it's quite enough to make integrations), you can read about it here: [ServerToServer](https://github.com/Payop/payop-api-doc/blob/master/Checkout/serverToServer.md) or [Hosted page](https://github.com/Payop/payop-api-doc/blob/master/Checkout/hostedPage.md). It's realy simple to start. 

As example you can look into [Checkout Demo App repository](https://github.com/Payop/checkout-demo-app). This is **ServerToServer** integration example. It's a bit outdated (in terms of using api), but general flow hasn't changed.


Anyway, this board only for technical issues, so, please contact  [support team](https://payop.com/en/contact-us) with any ather questions.
